"""ORM model registry.

Importing this package registers every table on ``Base.metadata`` so Alembic
autogenerate and the test-suite database bootstrap see the full schema.
"""

from __future__ import annotations

from app.db.base import EMBEDDING_DIM, Base, engine, get_db, session_scope
from app.models.access import (
    DEFAULT_ROLE_PERMISSIONS,
    AuditLog,
    Role,
    User,
    UserResearchItem,
)
from app.models.archive import (
    Collection,
    Document,
    DocumentChunk,
    DocumentMetadata,
    DocumentPage,
    DocumentVersion,
    Embedding,
    OcrResult,
    Source,
    Translation,
)
from app.models.enums import (
    AnswerKind,
    ClaimKind,
    DocumentType,
    EntityType,
    IndexStatus,
    JobKind,
    JobState,
    LanguageCode,
    MediaKind,
    OcrStatus,
    ProcessingState,
    PublicationStatus,
    RelationType,
    SourceTier,
    UserRole,
)
from app.models.knowledge import (
    Committee,
    ConstitutionalArticle,
    DocumentPerson,
    Event,
    EventDocument,
    EventPerson,
    GraphEdge,
    GraphNode,
    Organization,
    Person,
    Place,
    Relationship,
    Topic,
    TopicLink,
)
from app.models.media import Media, MediaRelation, MediaTag, MediaTranscript
from app.models.ops import (
    Citation,
    EvaluationRun,
    IntegrityCheck,
    OcrJob,
    ProcessingJob,
    RagQuery,
    Story,
    StoryChapter,
    StoryChapterLink,
    UiTranslation,
)

__all__ = [
    "EMBEDDING_DIM",
    "Base",
    "engine",
    "get_db",
    "session_scope",
    "Role",
    "User",
    "AuditLog",
    "UserResearchItem",
    "DEFAULT_ROLE_PERMISSIONS",
    "Source",
    "Collection",
    "Document",
    "DocumentVersion",
    "DocumentPage",
    "DocumentMetadata",
    "DocumentChunk",
    "Embedding",
    "Translation",
    "OcrResult",
    "Person",
    "Place",
    "Organization",
    "Committee",
    "Topic",
    "TopicLink",
    "DocumentPerson",
    "ConstitutionalArticle",
    "Event",
    "EventDocument",
    "EventPerson",
    "Relationship",
    "GraphNode",
    "GraphEdge",
    "Media",
    "MediaTranscript",
    "MediaTag",
    "MediaRelation",
    "ProcessingJob",
    "OcrJob",
    "IntegrityCheck",
    "RagQuery",
    "Citation",
    "Story",
    "StoryChapter",
    "StoryChapterLink",
    "UiTranslation",
    "EvaluationRun",
    "UserRole",
    "DocumentType",
    "LanguageCode",
    "ProcessingState",
    "OcrStatus",
    "IndexStatus",
    "PublicationStatus",
    "JobState",
    "JobKind",
    "EntityType",
    "RelationType",
    "SourceTier",
    "MediaKind",
    "ClaimKind",
    "AnswerKind",
]
