"""user session invalidation

Revision ID: 86c3caacf23b
Revises: ad2a75161e01
Create Date: 2026-09-27 12:04:00.801728+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '86c3caacf23b'
down_revision: str | None = 'ad2a75161e01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
