"""initial archive schema

Revision ID: ad2a75161e01
Revises: 
Create Date: 2026-09-27 11:59:56.881865+00:00
"""

from __future__ import annotations

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ad2a75161e01'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # pgvector and pg_trgm must exist before the embedding column and its ANN
    # index. `IF NOT EXISTS` is a no-op when a DBA has already provisioned them,
    # so the application role does not need superuser; run
    # `scripts/bootstrap_db.sh` once to create them.
    for ext in ("vector", "pg_trgm"):
        try:
            op.execute(f"CREATE EXTENSION IF NOT EXISTS {ext}")
        except sa.exc.DBAPIError as exc:  # pragma: no cover - provisioning aid
            raise RuntimeError(
                f"PostgreSQL extension '{ext}' is missing and could not be created by "
                f"the current role. Run scripts/bootstrap_db.sh as a superuser."
            ) from exc
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('cover_object_key', sa.Text(), nullable=True),
    sa.Column('accent', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections'))
    )
    op.create_index('ix_collections_published_sort', 'collections', ['is_published', 'sort_order'], unique=False)
    op.create_index(op.f('ix_collections_slug'), 'collections', ['slug'], unique=True)
    op.create_table('constitutional_articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('article_number', sa.String(length=20), nullable=False),
    sa.Column('part', sa.String(length=80), nullable=True),
    sa.Column('chapter', sa.String(length=160), nullable=True),
    sa.Column('heading', sa.String(length=240), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('amended_by', sa.String(length=300), nullable=True),
    sa.Column('effective_from', sa.String(length=80), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_constitutional_articles'))
    )
    op.create_index('ix_article_part_chapter', 'constitutional_articles', ['part', 'chapter'], unique=False)
    op.create_index(op.f('ix_constitutional_articles_article_number'), 'constitutional_articles', ['article_number'], unique=True)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dataset', sa.String(length=200), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('per_item', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_runs'))
    )
    op.create_index(op.f('ix_evaluation_runs_created_at'), 'evaluation_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_kind'), 'evaluation_runs', ['kind'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=240), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('degree', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_nodes'))
    )
    op.create_index(op.f('ix_graph_nodes_entity_type'), 'graph_nodes', ['entity_type'], unique=False)
    op.create_index(op.f('ix_graph_nodes_label'), 'graph_nodes', ['label'], unique=False)
    op.create_index(op.f('ix_graph_nodes_name'), 'graph_nodes', ['name'], unique=False)
    op.create_index('ix_graph_nodes_type_name', 'graph_nodes', ['entity_type', 'name'], unique=False)
    op.create_index(op.f('ix_graph_nodes_year'), 'graph_nodes', ['year'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('persons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('canonical_name', sa.String(length=240), nullable=False),
    sa.Column('alternate_names', sa.JSON(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons'))
    )
    op.create_index(op.f('ix_persons_canonical_name'), 'persons', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_persons_slug'), 'persons', ['slug'], unique=True)
    op.create_table('places',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places'))
    )
    op.create_index(op.f('ix_places_slug'), 'places', ['slug'], unique=True)
    op.create_table('rag_queries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_language', sa.String(length=8), nullable=False),
    sa.Column('answer_language', sa.String(length=8), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('answer_kind', sa.String(length=32), nullable=False),
    sa.Column('grounded', sa.Boolean(), nullable=False),
    sa.Column('groundedness', sa.Float(), nullable=True),
    sa.Column('retrieval', sa.JSON(), nullable=False),
    sa.Column('diagnostics', sa.JSON(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('llm_provider', sa.String(length=60), nullable=True),
    sa.Column('llm_model', sa.String(length=120), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('conflicting', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('session_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_queries'))
    )
    op.create_index(op.f('ix_rag_queries_answer_kind'), 'rag_queries', ['answer_kind'], unique=False)
    op.create_index(op.f('ix_rag_queries_created_at'), 'rag_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_rag_queries_grounded'), 'rag_queries', ['grounded'], unique=False)
    op.create_index(op.f('ix_rag_queries_session_key'), 'rag_queries', ['session_key'], unique=False)
    op.create_index(op.f('ix_rag_queries_user_id'), 'rag_queries', ['user_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=80), nullable=True),
    sa.Column('source_domain', sa.String(length=160), nullable=True),
    sa.Column('publisher', sa.String(length=240), nullable=True),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('rights_status', sa.String(length=80), nullable=True),
    sa.Column('license', sa.String(length=160), nullable=True),
    sa.Column('retrieval_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index('ix_sources_domain_tier', 'sources', ['source_domain', 'tier'], unique=False)
    op.create_index(op.f('ix_sources_source_domain'), 'sources', ['source_domain'], unique=False)
    op.create_index(op.f('ix_sources_tier'), 'sources', ['tier'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    op.create_table('ui_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ui_translations')),
    sa.UniqueConstraint('lang', 'key', name='uq_ui_translation')
    )
    op.create_index(op.f('ix_ui_translations_key'), 'ui_translations', ['key'], unique=False)
    op.create_index(op.f('ix_ui_translations_lang'), 'ui_translations', ['lang'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('query_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('validation_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['rag_queries.id'], name=op.f('fk_citations_query_id_rag_queries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citations'))
    )
    op.create_index(op.f('ix_citations_chunk_id'), 'citations', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_citations_document_id'), 'citations', ['document_id'], unique=False)
    op.create_index(op.f('ix_citations_page_id'), 'citations', ['page_id'], unique=False)
    op.create_index(op.f('ix_citations_query_id'), 'citations', ['query_id'], unique=False)
    op.create_table('committees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('formed_year', sa.Integer(), nullable=True),
    sa.Column('dissolved_year', sa.Integer(), nullable=True),
    sa.Column('chair_person_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chair_person_id'], ['persons.id'], name=op.f('fk_committees_chair_person_id_persons'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_committees'))
    )
    op.create_index(op.f('ix_committees_slug'), 'committees', ['slug'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('author_display', sa.String(length=300), nullable=True),
    sa.Column('speaker', sa.String(length=300), nullable=True),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('original_language', sa.String(length=8), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('year_from', sa.Integer(), nullable=True),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('date_precision', sa.String(length=24), nullable=True),
    sa.Column('location_text', sa.String(length=300), nullable=True),
    sa.Column('venue', sa.String(length=300), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=True),
    sa.Column('collection_id', sa.String(length=36), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('source_reference', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('rights', sa.String(length=200), nullable=True),
    sa.Column('provenance', sa.Text(), nullable=True),
    sa.Column('volume', sa.String(length=60), nullable=True),
    sa.Column('editorial_note', sa.Text(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('processing_state', sa.String(length=24), nullable=False),
    sa.Column('ocr_status', sa.String(length=24), nullable=False),
    sa.Column('embedding_status', sa.String(length=16), nullable=False),
    sa.Column('graph_status', sa.String(length=16), nullable=False),
    sa.Column('publication_status', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_documents_collection_id_collections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_documents_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_checksum_sha256'), 'documents', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_documents_collection_id'), 'documents', ['collection_id'], unique=False)
    op.create_index('ix_documents_collection_type', 'documents', ['collection_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_documents_document_date'), 'documents', ['document_date'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_embedding_status'), 'documents', ['embedding_status'], unique=False)
    op.create_index(op.f('ix_documents_external_id'), 'documents', ['external_id'], unique=False)
    op.create_index(op.f('ix_documents_is_demo'), 'documents', ['is_demo'], unique=False)
    op.create_index(op.f('ix_documents_language'), 'documents', ['language'], unique=False)
    op.create_index(op.f('ix_documents_ocr_status'), 'documents', ['ocr_status'], unique=False)
    op.create_index(op.f('ix_documents_processing_state'), 'documents', ['processing_state'], unique=False)
    op.create_index(op.f('ix_documents_publication_status'), 'documents', ['publication_status'], unique=False)
    op.create_index('ix_documents_published_year', 'documents', ['publication_status', 'year'], unique=False)
    op.create_index('ix_documents_search_tsv', 'documents', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_documents_slug'), 'documents', ['slug'], unique=True)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_index('ix_documents_title_trgm', 'documents', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_documents_type_lang', 'documents', ['document_type', 'language'], unique=False)
    op.create_index(op.f('ix_documents_year'), 'documents', ['year'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('date_label', sa.String(length=80), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('date_precision', sa.String(length=24), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=True),
    sa.Column('place_id', sa.String(length=36), nullable=True),
    sa.Column('place_label', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('significance', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_events_place_id_places'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_events_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_index(op.f('ix_events_year'), 'events', ['year'], unique=False)
    op.create_index('ix_events_year_type', 'events', ['year', 'event_type'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('media_date', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('creator', sa.String(length=240), nullable=True),
    sa.Column('speaker', sa.String(length=240), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('rights', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('thumbnail_key', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('publication_status', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_media_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    op.create_index(op.f('ix_media_kind'), 'media', ['kind'], unique=False)
    op.create_index('ix_media_kind_status', 'media', ['kind', 'publication_status'], unique=False)
    op.create_index(op.f('ix_media_language'), 'media', ['language'], unique=False)
    op.create_index(op.f('ix_media_media_date'), 'media', ['media_date'], unique=False)
    op.create_index('ix_media_search_tsv', 'media', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_media_slug'), 'media', ['slug'], unique=True)
    op.create_index(op.f('ix_media_year'), 'media', ['year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_role_active', 'users', ['role_id', 'is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_created_action', 'audit_logs', ['created_at', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_table('document_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=24), nullable=False),
    sa.Column('field_group', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_metadata_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_metadata')),
    sa.UniqueConstraint('document_id', 'key', name='uq_document_meta')
    )
    op.create_index(op.f('ix_document_metadata_document_id'), 'document_metadata', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_metadata_key'), 'document_metadata', ['key'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('rotation_degrees', sa.Float(), nullable=True),
    sa.Column('original_key', sa.Text(), nullable=True),
    sa.Column('processed_key', sa.Text(), nullable=True),
    sa.Column('thumbnail_key', sa.Text(), nullable=True),
    sa.Column('original_sha256', sa.String(length=64), nullable=True),
    sa.Column('processed_sha256', sa.String(length=64), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_corrected_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('ocr_language', sa.String(length=8), nullable=True),
    sa.Column('ocr_engine', sa.String(length=80), nullable=True),
    sa.Column('ocr_duration_ms', sa.Integer(), nullable=True),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.Column('detected_entities', sa.JSON(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_pages_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_pages')),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_document_page')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_index('ix_pages_doc_number', 'document_pages', ['document_id', 'page_number'], unique=False)
    op.create_table('document_people',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_people_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_document_people_person_id_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'person_id', name=op.f('pk_document_people'))
    )
    op.create_table('document_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('document_id', 'version', name='uq_document_version')
    )
    op.create_index(op.f('ix_document_versions_checksum_sha256'), 'document_versions', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index('ix_docver_doc_current', 'document_versions', ['document_id', 'is_current'], unique=False)
    op.create_table('event_documents',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('relation', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_event_documents_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_documents_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'document_id', name=op.f('pk_event_documents'))
    )
    op.create_table('event_people',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_people_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_event_people_person_id_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'person_id', name=op.f('pk_event_people'))
    )
    op.create_table('integrity_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('original_sha256', sa.String(length=64), nullable=False),
    sa.Column('current_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('checked_by', sa.String(length=36), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_integrity_checks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrity_checks'))
    )
    op.create_index(op.f('ix_integrity_checks_checked_at'), 'integrity_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_integrity_checks_document_id'), 'integrity_checks', ['document_id'], unique=False)
    op.create_index(op.f('ix_integrity_checks_scope'), 'integrity_checks', ['scope'], unique=False)
    op.create_index(op.f('ix_integrity_checks_status'), 'integrity_checks', ['status'], unique=False)
    op.create_index('ix_integrity_doc_status', 'integrity_checks', ['document_id', 'status'], unique=False)
    op.create_table('media_relations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_media_relations_media_id_media'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_relations')),
    sa.UniqueConstraint('media_id', 'target_type', 'target_id', name='uq_media_relation')
    )
    op.create_index(op.f('ix_media_relations_media_id'), 'media_relations', ['media_id'], unique=False)
    op.create_table('media_tags',
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_media_tags_media_id_media'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id', 'tag', name=op.f('pk_media_tags'))
    )
    op.create_index(op.f('ix_media_tags_tag'), 'media_tags', ['tag'], unique=False)
    op.create_table('media_transcripts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Float(), nullable=True),
    sa.Column('end_offset', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_searchable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_media_transcripts_media_id_media'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_transcripts')),
    sa.UniqueConstraint('media_id', 'language', 'kind', name='uq_media_transcript')
    )
    op.create_index(op.f('ix_media_transcripts_media_id'), 'media_transcripts', ['media_id'], unique=False)
    op.create_index('ix_transcript_search_tsv', 'media_transcripts', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('backend', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=48), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=120), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('media_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_processing_jobs_document_id_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    op.create_index('ix_jobs_state_kind', 'processing_jobs', ['state', 'kind'], unique=False)
    op.create_index(op.f('ix_processing_jobs_created_at'), 'processing_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_processing_jobs_document_id'), 'processing_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_kind'), 'processing_jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_processing_jobs_media_id'), 'processing_jobs', ['media_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_state'), 'processing_jobs', ['state'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('subtitle', sa.String(length=400), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('level', sa.String(length=24), nullable=False),
    sa.Column('cover_media_id', sa.String(length=36), nullable=True),
    sa.Column('narration_media_id', sa.String(length=36), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media.id'], name=op.f('fk_stories_cover_media_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['narration_media_id'], ['media.id'], name=op.f('fk_stories_narration_media_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories'))
    )
    op.create_index(op.f('ix_stories_slug'), 'stories', ['slug'], unique=True)
    op.create_table('topic_documents',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_topic_documents_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_topic_documents_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'topic_id', name=op.f('pk_topic_documents'))
    )
    op.create_table('user_research_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('session_key', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_research_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_research_items')),
    sa.UniqueConstraint('user_id', 'session_key', 'kind', 'target_type', 'target_id', name='uq_research_item')
    )
    op.create_index('ix_research_user_created', 'user_research_items', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_research_items_session_key'), 'user_research_items', ['session_key'], unique=False)
    op.create_index(op.f('ix_user_research_items_user_id'), 'user_research_items', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=300), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=300), nullable=True),
    sa.Column('volume', sa.String(length=60), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('embedding_model', sa.String(length=160), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('is_corrected_text', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], name=op.f('fk_document_chunks_page_id_document_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunk_index')
    )
    op.create_index('ix_chunks_doc_lang', 'document_chunks', ['document_id', 'language'], unique=False)
    op.create_index('ix_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunks_page', 'document_chunks', ['page_id'], unique=False)
    op.create_index('ix_chunks_search_tsv', 'document_chunks', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_chunks_content_hash'), 'document_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_language'), 'document_chunks', ['language'], unique=False)
    op.create_index(op.f('ix_document_chunks_page_id'), 'document_chunks', ['page_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_page_number'), 'document_chunks', ['page_number'], unique=False)
    op.create_table('ocr_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('engine', sa.String(length=80), nullable=True),
    sa.Column('engine_version', sa.String(length=60), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('preprocessing', sa.JSON(), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_ocr_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], name=op.f('fk_ocr_jobs_page_id_document_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ocr_jobs'))
    )
    op.create_index(op.f('ix_ocr_jobs_created_at'), 'ocr_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ocr_jobs_document_id'), 'ocr_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_ocr_jobs_job_id'), 'ocr_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_ocr_jobs_page_id'), 'ocr_jobs', ['page_id'], unique=False)
    op.create_index(op.f('ix_ocr_jobs_state'), 'ocr_jobs', ['state'], unique=False)
    op.create_table('ocr_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('engine', sa.String(length=80), nullable=False),
    sa.Column('engine_version', sa.String(length=60), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.Column('preprocessing', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_human_corrected', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_ocr_results_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], name=op.f('fk_ocr_results_page_id_document_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ocr_results'))
    )
    op.create_index(op.f('ix_ocr_results_created_at'), 'ocr_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_ocr_results_document_id'), 'ocr_results', ['document_id'], unique=False)
    op.create_index(op.f('ix_ocr_results_page_id'), 'ocr_results', ['page_id'], unique=False)
    op.create_index('ix_ocrresult_doc_current', 'ocr_results', ['document_id', 'is_current'], unique=False)
    op.create_table('story_chapters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('image_media_id', sa.String(length=36), nullable=True),
    sa.Column('audio_media_id', sa.String(length=36), nullable=True),
    sa.Column('video_media_id', sa.String(length=36), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('pull_quote', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_media_id'], ['media.id'], name=op.f('fk_story_chapters_audio_media_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_story_chapters_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_story_chapters_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_media_id'], ['media.id'], name=op.f('fk_story_chapters_image_media_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_chapters_story_id_stories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_media_id'], ['media.id'], name=op.f('fk_story_chapters_video_media_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_chapters')),
    sa.UniqueConstraint('story_id', 'chapter_number', name='uq_story_chapter')
    )
    op.create_index(op.f('ix_story_chapters_story_id'), 'story_chapters', ['story_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('fk_embeddings_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embeddings'))
    )
    op.create_index(op.f('ix_embeddings_chunk_id'), 'embeddings', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_embeddings_content_hash'), 'embeddings', ['content_hash'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_type', sa.String(length=40), nullable=False),
    sa.Column('from_id', sa.String(length=64), nullable=False),
    sa.Column('to_type', sa.String(length=40), nullable=False),
    sa.Column('to_id', sa.String(length=64), nullable=False),
    sa.Column('relation', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('evidence_chunk_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_chunk_id'], ['document_chunks.id'], name=op.f('fk_relationships_evidence_chunk_id_document_chunks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationships')),
    sa.UniqueConstraint('from_type', 'from_id', 'to_type', 'to_id', 'relation', name='uq_rel_edge')
    )
    op.create_index('ix_rel_from', 'relationships', ['from_type', 'from_id', 'status'], unique=False)
    op.create_index('ix_rel_to', 'relationships', ['to_type', 'to_id', 'status'], unique=False)
    op.create_index(op.f('ix_relationships_from_id'), 'relationships', ['from_id'], unique=False)
    op.create_index(op.f('ix_relationships_from_type'), 'relationships', ['from_type'], unique=False)
    op.create_index(op.f('ix_relationships_relation'), 'relationships', ['relation'], unique=False)
    op.create_index(op.f('ix_relationships_status'), 'relationships', ['status'], unique=False)
    op.create_index(op.f('ix_relationships_to_id'), 'relationships', ['to_id'], unique=False)
    op.create_index(op.f('ix_relationships_to_type'), 'relationships', ['to_type'], unique=False)
    op.create_table('story_chapter_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=240), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['story_chapters.id'], name=op.f('fk_story_chapter_links_chapter_id_story_chapters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_chapter_links'))
    )
    op.create_index('ix_chapter_link_target', 'story_chapter_links', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_story_chapter_links_chapter_id'), 'story_chapter_links', ['chapter_id'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_id', sa.String(length=36), nullable=True),
    sa.Column('source_language', sa.String(length=8), nullable=False),
    sa.Column('target_language', sa.String(length=8), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('fk_translations_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_translations_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], name=op.f('fk_translations_page_id_document_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_translations')),
    sa.UniqueConstraint('chunk_id', 'target_language', name='uq_chunk_translation')
    )
    op.create_index('ix_translation_target', 'translations', ['target_language', 'source_language'], unique=False)
    op.create_index(op.f('ix_translations_chunk_id'), 'translations', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_translations_document_id'), 'translations', ['document_id'], unique=False)
    op.create_index(op.f('ix_translations_page_id'), 'translations', ['page_id'], unique=False)
    op.create_index(op.f('ix_translations_target_language'), 'translations', ['target_language'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('src_id', sa.String(length=120), nullable=False),
    sa.Column('dst_id', sa.String(length=120), nullable=False),
    sa.Column('relation', sa.String(length=40), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('relationship_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dst_id'], ['graph_nodes.id'], name=op.f('fk_graph_edges_dst_id_graph_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], name=op.f('fk_graph_edges_relationship_id_relationships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['src_id'], ['graph_nodes.id'], name=op.f('fk_graph_edges_src_id_graph_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_edges'))
    )
    op.create_index('ix_graph_edge_dst_rel', 'graph_edges', ['dst_id', 'relation'], unique=False)
    op.create_index('ix_graph_edge_src_rel', 'graph_edges', ['src_id', 'relation'], unique=False)
    op.create_index(op.f('ix_graph_edges_dst_id'), 'graph_edges', ['dst_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_relation'), 'graph_edges', ['relation'], unique=False)
    op.create_index(op.f('ix_graph_edges_src_id'), 'graph_edges', ['src_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_edges_src_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_relation'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_dst_id'), table_name='graph_edges')
    op.drop_index('ix_graph_edge_src_rel', table_name='graph_edges')
    op.drop_index('ix_graph_edge_dst_rel', table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_translations_target_language'), table_name='translations')
    op.drop_index(op.f('ix_translations_page_id'), table_name='translations')
    op.drop_index(op.f('ix_translations_document_id'), table_name='translations')
    op.drop_index(op.f('ix_translations_chunk_id'), table_name='translations')
    op.drop_index('ix_translation_target', table_name='translations')
    op.drop_table('translations')
    op.drop_index(op.f('ix_story_chapter_links_chapter_id'), table_name='story_chapter_links')
    op.drop_index('ix_chapter_link_target', table_name='story_chapter_links')
    op.drop_table('story_chapter_links')
    op.drop_index(op.f('ix_relationships_to_type'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_to_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_status'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_relation'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_from_type'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_from_id'), table_name='relationships')
    op.drop_index('ix_rel_to', table_name='relationships')
    op.drop_index('ix_rel_from', table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_embeddings_content_hash'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_chunk_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_story_chapters_story_id'), table_name='story_chapters')
    op.drop_table('story_chapters')
    op.drop_index('ix_ocrresult_doc_current', table_name='ocr_results')
    op.drop_index(op.f('ix_ocr_results_page_id'), table_name='ocr_results')
    op.drop_index(op.f('ix_ocr_results_document_id'), table_name='ocr_results')
    op.drop_index(op.f('ix_ocr_results_created_at'), table_name='ocr_results')
    op.drop_table('ocr_results')
    op.drop_index(op.f('ix_ocr_jobs_state'), table_name='ocr_jobs')
    op.drop_index(op.f('ix_ocr_jobs_page_id'), table_name='ocr_jobs')
    op.drop_index(op.f('ix_ocr_jobs_job_id'), table_name='ocr_jobs')
    op.drop_index(op.f('ix_ocr_jobs_document_id'), table_name='ocr_jobs')
    op.drop_index(op.f('ix_ocr_jobs_created_at'), table_name='ocr_jobs')
    op.drop_table('ocr_jobs')
    op.drop_index(op.f('ix_document_chunks_page_number'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_page_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_language'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_content_hash'), table_name='document_chunks')
    op.drop_index('ix_chunks_search_tsv', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_page', table_name='document_chunks')
    op.drop_index('ix_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_chunks_doc_lang', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_user_research_items_user_id'), table_name='user_research_items')
    op.drop_index(op.f('ix_user_research_items_session_key'), table_name='user_research_items')
    op.drop_index('ix_research_user_created', table_name='user_research_items')
    op.drop_table('user_research_items')
    op.drop_table('topic_documents')
    op.drop_index(op.f('ix_stories_slug'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_processing_jobs_state'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_media_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_kind'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_document_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_created_at'), table_name='processing_jobs')
    op.drop_index('ix_jobs_state_kind', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('ix_transcript_search_tsv', table_name='media_transcripts', postgresql_using='gin')
    op.drop_index(op.f('ix_media_transcripts_media_id'), table_name='media_transcripts')
    op.drop_table('media_transcripts')
    op.drop_index(op.f('ix_media_tags_tag'), table_name='media_tags')
    op.drop_table('media_tags')
    op.drop_index(op.f('ix_media_relations_media_id'), table_name='media_relations')
    op.drop_table('media_relations')
    op.drop_index('ix_integrity_doc_status', table_name='integrity_checks')
    op.drop_index(op.f('ix_integrity_checks_status'), table_name='integrity_checks')
    op.drop_index(op.f('ix_integrity_checks_scope'), table_name='integrity_checks')
    op.drop_index(op.f('ix_integrity_checks_document_id'), table_name='integrity_checks')
    op.drop_index(op.f('ix_integrity_checks_checked_at'), table_name='integrity_checks')
    op.drop_table('integrity_checks')
    op.drop_table('event_people')
    op.drop_table('event_documents')
    op.drop_index('ix_docver_doc_current', table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_checksum_sha256'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_table('document_people')
    op.drop_index('ix_pages_doc_number', table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_document_metadata_key'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_document_id'), table_name='document_metadata')
    op.drop_table('document_metadata')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_created_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_media_year'), table_name='media')
    op.drop_index(op.f('ix_media_slug'), table_name='media')
    op.drop_index('ix_media_search_tsv', table_name='media', postgresql_using='gin')
    op.drop_index(op.f('ix_media_media_date'), table_name='media')
    op.drop_index(op.f('ix_media_language'), table_name='media')
    op.drop_index('ix_media_kind_status', table_name='media')
    op.drop_index(op.f('ix_media_kind'), table_name='media')
    op.drop_table('media')
    op.drop_index('ix_events_year_type', table_name='events')
    op.drop_index(op.f('ix_events_year'), table_name='events')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_documents_year'), table_name='documents')
    op.drop_index('ix_documents_type_lang', table_name='documents')
    op.drop_index('ix_documents_title_trgm', table_name='documents', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_slug'), table_name='documents')
    op.drop_index('ix_documents_search_tsv', table_name='documents', postgresql_using='gin')
    op.drop_index('ix_documents_published_year', table_name='documents')
    op.drop_index(op.f('ix_documents_publication_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_processing_state'), table_name='documents')
    op.drop_index(op.f('ix_documents_ocr_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_language'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_demo'), table_name='documents')
    op.drop_index(op.f('ix_documents_external_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_embedding_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_index('ix_documents_collection_type', table_name='documents')
    op.drop_index(op.f('ix_documents_collection_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum_sha256'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_committees_slug'), table_name='committees')
    op.drop_table('committees')
    op.drop_index(op.f('ix_citations_query_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_page_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_document_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_chunk_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_ui_translations_lang'), table_name='ui_translations')
    op.drop_index(op.f('ix_ui_translations_key'), table_name='ui_translations')
    op.drop_table('ui_translations')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_sources_tier'), table_name='sources')
    op.drop_index(op.f('ix_sources_source_domain'), table_name='sources')
    op.drop_index('ix_sources_domain_tier', table_name='sources')
    op.drop_table('sources')
    op.drop_table('roles')
    op.drop_index(op.f('ix_rag_queries_user_id'), table_name='rag_queries')
    op.drop_index(op.f('ix_rag_queries_session_key'), table_name='rag_queries')
    op.drop_index(op.f('ix_rag_queries_grounded'), table_name='rag_queries')
    op.drop_index(op.f('ix_rag_queries_created_at'), table_name='rag_queries')
    op.drop_index(op.f('ix_rag_queries_answer_kind'), table_name='rag_queries')
    op.drop_table('rag_queries')
    op.drop_index(op.f('ix_places_slug'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_persons_slug'), table_name='persons')
    op.drop_index(op.f('ix_persons_canonical_name'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_graph_nodes_year'), table_name='graph_nodes')
    op.drop_index('ix_graph_nodes_type_name', table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_name'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_label'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_entity_type'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_index(op.f('ix_evaluation_runs_kind'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_created_at'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_constitutional_articles_article_number'), table_name='constitutional_articles')
    op.drop_index('ix_article_part_chapter', table_name='constitutional_articles')
    op.drop_table('constitutional_articles')
    op.drop_index(op.f('ix_collections_slug'), table_name='collections')
    op.drop_index('ix_collections_published_sort', table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
